# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ac8d6855b8224c2ece68a8f81618af9d5b949e3428752adc0922da1c1c2d64157e1e277192384e37ed13de6af13cb1ef5a91e40aaec5506623134390515f18a

test:
  secret_key_base: 2e74665786b162dc57f352bf9b1767d895a02345d8e041a69a31b8810eb78ad99968cd6fe35cf97c58fab7ee6920d7f870886a8050a5b9e8f11efb5c86d5a04c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
